main: com.fren_gor.commandCraftCore.CommandCraftCore
name: CommandCraftCore
description: Create cmcs scripts to run sequences of commands on spigot servers! 
version: alpha-1.0
author: fren_gor
website: https://github.com/frengordev/CommandCraftCore

api-version: 1.13

commands:
  createscript:
    description: Create a default script from a template
    permission: commandCraftCore.createScript
  updatescript:
    description: Create a default script from a template
    permission: commandCraftCore.createScript
  worldtp:
    description: Teleport a player to a certain world
    permission: commandCraftCore.worldtp
  commandcraftcore:
    description: The main command of the plugin
    aliases: [ccc]
    permission: commandCraftCore.mainCommand
  varhelp:
    description: The main command of the plugin
    permission: commandCraftCore.varhelp
    

permissions:
  commandCraftCore.varhelp:
    description: use the command /varhelp
    default: op
  commandCraftCore.mainCommand:
    description: use the command /commandCraftCore
    default: op
  commandCraftCore.createScript:
    description: use the command /createscript
    default: op
  commandCraftCore.worldtp:
    description: use the command /worldtp
    default: true