#####################################################################################################
#   _________                                           .____________                _____  __      #
#   \_   ___ \  ____   _____   _____ _____    ____    __| _/\_   ___ \____________ _/ ____\/  |_    #
#   /    \  \/ /  _ \ /     \ /     \\__  \  /    \  / __ | /    \  \/\_  __ \__  \\   __\\   __\   #
#   \     \___(  <_> )  Y Y  \  Y Y  \/ __ \|   |  \/ /_/ | \     \____|  | \// __ \|  |   |  |     #
#    \______  /\____/|__|_|  /__|_|  (____  /___|  /\____ |  \______  /|__|  (____  /__|   |__|     #
#           \/             \/      \/     \/     \/      \/         \/            \/                #
#                                  _________                                                        #
#                                  \_   ___ \  ___________   ____                                   #
#                                  /    \  \/ /  _ \_  __ \_/ __ \                                  #
#                                  \     \___(  <_> )  | \/\  ___/                                  #
#                                   \______  /\____/|__|    \___  >                                 #
#                                          \/                   \/                                  #
#####################################################################################################

debug-mode: false

view-execute-time: true
